version: 2.1

jobs:
  create_infrastructure:
    docker:
      - image: 'amazon/aws-cli'
    steps:
      - checkout
      - run: echo $PWD
      - run: aws cloudformation create-stack --stack-name 'CircleCi' --template-body file://cloudformation.yml  --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM" --region=$AWS_DEFAULT_REGION
workflows:
  my_workflow:
    jobs:
      - create_infrastructure:
          context:
            - AWS
