version: 2.1

orbs:
  slack: circleci/slack@4.3.0
  
jobs:
  save_hello_world_output:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - run: return 1
      - slack/notify:
          event: fail
          mentions: '@m'
          template: basic_fail_1
workflows:
  my_workflow:
    jobs:
      - save_hello_world_output
